[2025-07-20T05:29:04.895+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retrain_model_dag.retrain_best_model manual__2025-07-20T05:28:51.516755+00:00 [queued]>
[2025-07-20T05:29:04.906+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retrain_model_dag.retrain_best_model manual__2025-07-20T05:28:51.516755+00:00 [queued]>
[2025-07-20T05:29:04.907+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-20T05:29:05.054+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): retrain_best_model> on 2025-07-20 05:28:51.516755+00:00
[2025-07-20T05:29:05.071+0000] {standard_task_runner.py:60} INFO - Started process 78 to run task
[2025-07-20T05:29:05.089+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'retrain_model_dag', 'retrain_best_model', 'manual__2025-07-20T05:28:51.516755+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/retrain_model_dag.py', '--cfg-path', '/tmp/tmp39g_5qdw']
[2025-07-20T05:29:05.095+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask retrain_best_model
[2025-07-20T05:29:05.240+0000] {task_command.py:423} INFO - Running <TaskInstance: retrain_model_dag.retrain_best_model manual__2025-07-20T05:28:51.516755+00:00 [running]> on host b9e8b1b5977e
[2025-07-20T05:29:05.412+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retrain_model_dag' AIRFLOW_CTX_TASK_ID='retrain_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T05:28:51.516755+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-20T05:28:51.516755+00:00'
[2025-07-20T05:29:05.415+0000] {logging_mixin.py:188} INFO - üì¶ Starting retraining process
[2025-07-20T05:29:05.415+0000] {logging_mixin.py:188} INFO - üóÑÔ∏è Loading data...
[2025-07-20T05:29:05.429+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/retrain_model_dag.py", line 10, in retrain_model
    main()
  File "/opt/airflow/dags/main.py", line 134, in main
    df = pd.read_csv("Lead Scoring.csv")
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'Lead Scoring.csv'
[2025-07-20T05:29:05.464+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=retrain_model_dag, task_id=retrain_best_model, execution_date=20250720T052851, start_date=20250720T052904, end_date=20250720T052905
[2025-07-20T05:29:05.523+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 47 for task retrain_best_model ([Errno 2] No such file or directory: 'Lead Scoring.csv'; 78)
[2025-07-20T05:29:05.582+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-20T05:29:05.608+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
